CreateDir /etc/skel
CreateDir /etc/modprobe.d
CreateDir /etc/systemd/journald.conf.d
CreateDir /etc/gnupg/crls.d
CreateDir /etc/gnupg/openpgp-revocs.d
CreateDir /etc/gnupg/private-keys-v1.d
CreateDir /etc/dbus-1/system.d 
CreateDir /etc/systemd/system/basic.target.wants/

CopyFile /etc/dirmngr.conf
CopyFile /etc/gnupg/gpg-agent.conf
CopyFile /etc/gnupg/gpg.conf
CopyFile /etc/gnupg/private-keys-v1.d/11D6863DCB49D37DACC54D55C287CAA9FD3ACAAD.key
CopyFile /etc/gnupg/private-keys-v1.d/34A70B981069547DDCCEAEFD3FADC8BCB6B113E7.key
CopyFile /etc/gnupg/pubring.gpg
CopyFile /etc/gnupg/pubring.gpg~
CopyFile /etc/gnupg/secring.gpg
CopyFile /etc/gnupg/trustdb.gpg
CopyFile /etc/locale.gen
CopyFile /etc/systemd/system/basic.target.wants/NetworkManager.service
CopyFile /etc/systemd/system/basic.target.wants/systemd-networkd.service
CopyFile /etc/systemd/system/basic.target.wants/systemd-resolved.service
CopyFile /etc/systemd/system/basic.target.wants/zfs.target
CopyFile /etc/systemd/system/dbus.socket
CopyFile /etc/systemd/system/basic.target
CopyFile /etc/systemd/system/systemd-homed.service
CopyFile /etc/systemd/system/zfs.target
CopyFile /usr/lib/systemd/user/dbus-broker.service
CopyFile /etc/pacman.d/openpgp-revocs.d/BAB58BBAEF1C5C59265C031CC4ABC716692AA6B2.rev
CopyFile /etc/pacman.d/pacman.custom.example
CopyFile /etc/pacman.d/private-keys-v1.d/C7031B5B5495485A638199A919E1D13E8A19767A.key
CopyFile /etc/pacman.d/pubring.kbx
CopyFile /etc/pacman.d/pubring.kbx~
CopyFile /etc/pacman.d/tofu.db
CopyFile /etc/pacman.d/trustdb.gpg
CopyFile /etc/paru.conf
CreateFile /var/log/btmp 00600  > /dev/null
CreateFile /var/log/lastlog 00600 > /dev/null
IgnorePath /etc/gnupg/S.dirmngr 
IgnorePath /etc/gnupg/S.gpg-agent.ssh
IgnorePath /etc/gnupg/S.gpg-agent
IgnorePath /etc/gnupg/S.gpg-agent.browser
IgnorePath /etc/gnupg/S.gpg-agent.extra
SetFileProperty '/var/log/journal/remote' mode 00700
SetFileProperty /var/log/journal mode 00700
CopyFile /etc/os-release
CopyFile /etc/pacman.conf
CopyFile /etc/pacman-more.conf
CopyFile /etc/pkcs11/pkcs11.conf
CopyFile /etc/pacman.d/gpg-agent.conf
CopyFile /etc/pacman.d/gpg.conf
CopyFile /etc/resolv.conf
CopyFile /etc/modprobe.d/blacklist.conf

CopyFile /etc/pacman.d/cachyos-mirrorlist-backup
CopyFile /etc/pacman.d/cachyos-v3-mirrorlist-backup
CopyFile /etc/pacman.d/cachyos-v4-mirrorlist-backup
CopyFile /etc/pacman.d/mirrorlist-backup

CopyFile /etc/shells
CopyFile /usr/bin/aconfmgr
CopyFile /etc/skel/.bashrc
CopyFile /etc/dbus-1/system.d/avahi-dbus.conf
IgnorePath '/var/lib/pacman/*'
IgnorePath '/etc/ssl/certs/*'
IgnorePath '/etc/ca-certificates/*'
IgnorePath '/etc/pacman.d/gnupg/S.dirmngr'
IgnorePath '/etc/pacman.d/gnupg/S.gpg-agent'
IgnorePath '/etc/pacman.d/gnupg/S.gpg-agent.browser'
IgnorePath '/etc/pacman.d/gnupg/S.gpg-agent.extra'
IgnorePath '/etc/pacman.d/gnupg/S.gpg-agent.ssh'
IgnorePath '/etc/pacman.d/gnupg/S.keyboxd'
CopyFile '/etc/pacman.d/gnupg/pubring.gpg~'
IgnorePath '/etc/ssh/*'
IgnorePath '/usr/share/factory/*'
IgnorePath '/etc/xdg/autostart/spice-vdagent.desktop'
IgnorePath '/usr/local/*'
IgnorePath '/usr/share/mime/*'
IgnorePath '/usr/share/mime/*/*'
IgnorePath '/var/tmp/*'
IgnorePath '/var/log/*'
IgnorePath '/usr/share/icons/*'
IgnorePath '/var/lib/upower/*'
IgnorePath '/usr/share/modules/*'
IgnorePath '/usr/share/modules/linux-cachyos-lts-nvidia/*'
IgnorePath '/etc/ld.so.cache'
IgnorePath /usr/lib/aconfmgr/*
CopyFile /etc/security/access.conf
CreateDir /etc/security/
CreateDir files/etc/systemd/system/basic.target.wants/
