IgnorePath '/var/lib/pacman/*'
IgnorePath '/etc/ssl/certs/*'
IgnorePath '/etc/ca-certificates/*'
IgnorePath '/etc/pacman.d/gnupg/S.dirmngr'
IgnorePath '/etc/pacman.d/gnupg/S.gpg-agent'
IgnorePath '/etc/pacman.d/gnupg/S.gpg-agent.browser'
IgnorePath '/etc/pacman.d/gnupg/S.gpg-agent.extra'
IgnorePath '/etc/pacman.d/gnupg/S.gpg-agent.ssh'
IgnorePath '/etc/pacman.d/gnupg/S.keyboxd'
IgnorePath '/etc/pacman.d/gnupg/pubring.gpg~'
IgnorePath '/etc/ssh/*'
IgnorePath '/usr/share/factory/*'
IgnorePath '/etc/xdg/autostart/spice-vdagent.desktop'
IgnorePath '/usr/local/*'
IgnorePath '/usr/share/mime/*'
IgnorePath '/usr/share/mime/*/*'
IgnorePath '/var/tmp/*'
IgnorePath '/var/log/*'
IgnorePath '/usr/share/icons/*'
IgnorePath '/var/lib/upower/*'


