blacklist pkcs8_key_parser
# DEF_BAD
blacklist pkcs8_key_parser     
blacklist wmi                  
blacklist wmi_bmof             
blacklist snd_hda_intel        
blacklist kvm 
blacklist kvm_intel
blacklist i2c_dev              
blacklist i2c_piix4            
blacklist i2c_smbus            
blacklist crc32c_intel         
blacklist ghash_clmulni_intel  
blacklist intel_rapl_common    
blacklist intel_rapl_msr       
blacklist snd_intel_dspcfg     
blacklist snd_intel_sdw_acpi   
blacklist sha1_ssse3           
blacklist sha256_ssse3         
blacklist sha512_ssse3         
blacklist gigabyte_wmi         
blacklist aesni_intel          
## Not Necessarily bad, but unnecessary rn
blacklist raid6_pq             
blacklist minix                
blacklist jbd2                 
blacklist ufs                  
blacklist tun                  
