net.ipv4.conf.default.send_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.default.drop_gratuitous_arp = 1
net.ipv4.conf.default.drop_unicast_in_l2_multicast = 1
net.ipv4.conf.default.shared_media = 0
net.ipv4.conf.default.secure_redirects = 0
net.ipv4.conf.default.arp_filter = 1
net.ipv4.conf.default.arp_announce = 0
net.ipv4.conf.default.forwarding = 0
