net.ipv6.conf.enp5s0.autoconf = 0
net.ipv6.conf.default.autoconf = 0
net.ipv6.conf.default.accept_ra = 0
net.ipv6.conf.default.accept_ra_from_local = 0
net.ipv6.conf.default.drop_unsolicited_na = 1
net.ipv6.conf.default.drop_unicast_in_l2_multicast = 1
