net.ipv4.conf.lo.accept_local = 0
net.ipv4.conf.lo.accept_redirects = 0
net.ipv4.conf.lo.arp_accept = 0
net.ipv6.conf.lo.accept_ra = 0
net.ipv6.conf.lo.addr_gen_mode = 0
net.ipv6.conf.lo.autoconf = 0
net.ipv6.conf.lo.accept_redirects = 0
net.ipv6.conf.lo.dad_transmits = 0
net.ipv6.conf.lo.router_solicitations = 0
