net.ipv4.conf.all.accept_redirects=0
net.ipv4.conf.all.secure_redirects=0
net.ipv4.conf.all.send_redirects=0
net.ipv4.conf.default.accept_redirects=0
net.ipv4.conf.default.secure_redirects=0
net.ipv4.conf.default.send_redirects=0
net.ipv4.conf.enp5s0.accept_redirects=0
net.ipv4.conf.enp5s0.secure_redirects=0
net.ipv4.conf.enp5s0.send_redirects=0
net.ipv4.conf.lo.accept_redirects=0
net.ipv4.conf.lo.secure_redirects=0
net.ipv4.conf.lo.send_redirects=0
net.ipv6.conf.all.accept_redirects=0
net.ipv6.conf.default.accept_redirects=0
net.ipv6.conf.enp5s0.accept_redirects=0
net.ipv6.conf.lo.accept_redirects=0
net.ipv4.route.redirect_load=0
net.ipv4.route.redirect_number=0
net.ipv4.route.redirect_silence=0
