net.ipv4.conf.all.accept_redirects=0
net.ipv4.conf.all.accept_source_route=0
net.ipv4.conf.all.arp_accept=0
net.ipv4.conf.all.arp_announce=0
net.ipv4.conf.all.arp_evict_nocarrier=0
net.ipv4.conf.all.arp_filter=0
net.ipv4.conf.all.arp_ignore=0
net.ipv4.conf.all.arp_notify=0
net.ipv4.conf.all.bc_forwarding=0
net.ipv4.conf.all.bootp_relay=0
net.ipv4.conf.all.disable_policy=0
net.ipv4.conf.all.disable_xfrm=0
net.ipv4.conf.all.drop_gratuitous_arp=0
net.ipv4.conf.all.drop_unicast_in_l2_multicast=0
net.ipv4.conf.all.force_igmp_version=0
net.ipv4.conf.all.forwarding=0
net.ipv4.conf.all.igmpv2_unsolicited_report_interval=0
net.ipv4.conf.all.igmpv3_unsolicited_report_interval=0
net.ipv4.conf.all.ignore_routes_with_linkdown=0
net.ipv4.conf.all.log_martians=0
net.ipv4.conf.all.mc_forwarding=0
net.ipv4.conf.all.medium_id=0
net.ipv4.conf.all.promote_secondaries=0
net.ipv4.conf.all.proxy_arp=0
net.ipv4.conf.all.proxy_arp_pvlan=0
net.ipv4.conf.all.route_localnet=0
net.ipv4.conf.all.rp_filter=0
net.ipv4.conf.all.secure_redirects=0
net.ipv4.conf.all.send_redirects=0
net.ipv4.conf.all.shared_media=0
net.ipv4.conf.all.src_valid_mark=0
net.ipv4.conf.all.tag=0
net.ipv6.conf.all.accept_dad=0
net.ipv6.conf.all.accept_ra=0
net.ipv6.conf.all.accept_ra_defrtr=0
net.ipv6.conf.all.accept_ra_from_local=0
net.ipv6.conf.all.accept_ra_min_hop_limit=0
net.ipv6.conf.all.accept_ra_min_lft=0
net.ipv6.conf.all.accept_ra_mtu=0
net.ipv6.conf.all.accept_ra_pinfo=0
net.ipv6.conf.all.accept_ra_rt_info_max_plen=0
net.ipv6.conf.all.accept_ra_rt_info_min_plen=0
net.ipv6.conf.all.accept_ra_rtr_pref=0
net.ipv6.conf.all.accept_redirects=0
net.ipv6.conf.all.accept_source_route=0
net.ipv6.conf.all.accept_untracked_na=0
net.ipv6.conf.all.addr_gen_mode=0
net.ipv6.conf.all.autoconf=0
net.ipv6.conf.all.dad_transmits=0
net.ipv6.conf.all.disable_ipv6=0
net.ipv6.conf.all.disable_policy=0
net.ipv6.conf.all.drop_unicast_in_l2_multicast=0
net.ipv6.conf.all.drop_unsolicited_na=0
net.ipv6.conf.all.enhanced_dad=0
net.ipv6.conf.all.force_forwarding=0
net.ipv6.conf.all.force_mld_version=0
net.ipv6.conf.all.force_tllao=0
net.ipv6.conf.all.forwarding=0
net.ipv6.conf.all.hop_limit=0
net.ipv6.conf.all.ignore_routes_with_linkdown=0
net.ipv6.conf.all.ioam6_enabled=0
net.ipv6.conf.all.ioam6_id=0
net.ipv6.conf.all.ioam6_id_wide=0
net.ipv6.conf.all.keep_addr_on_down=0
net.ipv6.conf.all.max_addresses=0
net.ipv6.conf.all.max_desync_factor=0
net.ipv6.conf.all.mc_forwarding=0
net.ipv6.conf.all.mldv1_unsolicited_report_interval=0
net.ipv6.conf.all.mldv2_unsolicited_report_interval=0
net.ipv6.conf.all.mtu=0
net.ipv6.conf.all.ndisc_evict_nocarrier=0
net.ipv6.conf.all.ndisc_notify=0
net.ipv6.conf.all.ndisc_tclass=0
net.ipv6.conf.all.optimistic_dad=0
net.ipv6.conf.all.proxy_ndp=0
net.ipv6.conf.all.ra_defrtr_metric=0
net.ipv6.conf.all.ra_honor_pio_life=0
net.ipv6.conf.all.ra_honor_pio_pflag=0
net.ipv6.conf.all.regen_max_retry=0
net.ipv6.conf.all.regen_min_advance=0
net.ipv6.conf.all.router_probe_interval=0
net.ipv6.conf.all.router_solicitation_delay=0
net.ipv6.conf.all.router_solicitation_interval=0
net.ipv6.conf.all.router_solicitation_max_interval=0
net.ipv6.conf.all.router_solicitations=0
net.ipv6.conf.all.rpl_seg_enabled=0
net.ipv6.conf.all.seg6_enabled=0
net.ipv6.conf.all.seg6_require_hmac=0
net.ipv6.conf.all.suppress_frag_ndisc=0
net.ipv6.conf.all.temp_prefered_lft=0
net.ipv6.conf.all.temp_valid_lft=0
net.ipv6.conf.all.use_oif_addrs_only=0
net.ipv6.conf.all.use_optimistic=0
net.ipv6.conf.all.use_tempaddr=0
net.ipv6.conf.all.addr_gen_mode = 1
