#Configuration:1:0:Options controlling the configuration:0:0::::
#max-replies:16:0:do not return more than N items in one query:2:2:N:10::
#Network:1:0:Network related options:0:0::::
#use-tor:0:0:route all network traffic via Tor:0:0::::
#resolver-timeout:16:3::2:2::0::
#nameserver:0:3::1:1::::

#HTTP:1:1:Configuration for HTTP servers:0:0::::
#disable-http:0:1:inhibit the use of HTTP:0:0::::
#ignore-http-dp:0:1:ignore HTTP CRL distribution points:0:0::::
#http-proxy:0:1:redirect all HTTP requests to URL:1:1:URL:::
#honor-http-proxy:0:1:use system's HTTP proxy setting:0:0::::

#Keyserver:1:0:Configuration for OpenPGP servers:0:0::::
#keyserver:16:0:use keyserver at URL:1:1:URL:"hkps%3a//keyserver.ubuntu.com::
#add-servers:0:2:add new servers discovered in CRL distribution points to serverlist:0:0::::

#OCSP:1:0:Configuration for OCSP:0:0::::
#allow-ocsp:0:0:allow sending OCSP requests:0:0::::
#ignore-ocsp-service-url:0:1:ignore certificate contained OCSP service URLs:0:0::::
#ocsp-responder:0:1:use OCSP responder at URL:1:1:URL:::
#ocsp-signer:0:1:OCSP response signed by FPR:1:1:FPR:::

#force:0:0:force loading of outdated CRLs:0:0::::
#batch:0:0::0:0::::

#faked-system-time:0:3::1:1::::


## LDAP CONFIGURATION


#ldaptimeout:16:0:set LDAP timeout to N seconds:2:2:N:15::
#LDAP:1:0:Configuration for X.509 servers:0:0::::
#disable-ldap:0:1:inhibit the use of LDAP:0:0::::
#ignore-ldap-dp:0:1:ignore LDAP CRL distribution points:0:0::::
#ldap-proxy:0:0:use HOST for LDAP queries:1:1:HOST:::
#only-ldap-proxy:0:1:do not use fallback hosts with --ldap-proxy:0:0::::
#ldapserver:4:0:use this keyserver to lookup keys:33:1:SPEC:::





##  Monitoring, debugging, and Logs

#Monitor:1:0:Options controlling the diagnostic output:0:0::::
#verbose:4:0:verbose:0:0::::
#quiet:0:0:be somewhat more quiet:0:0::::
#no-greeting:0:3::0:0::::
#debug-level:16:1:set the debugging level to LEVEL:1:1:LEVEL:"none::
#log-file:0:1:write server mode logs to FILE:32:1:FILE:::
#allow-version-check:0:0:allow online software version check:0:0::::
