# each line prefixed by a plus sign (+) followed by an absolute path defines the
# scope of where to look
+/boot
+/efi
+/etc
+/opt
+/srv
+/usr
+/var

# each line prefixed by a minus sign (-) followed by an absolute path defines
# the excludes list
-/boot/efi
-/boot/EFI
-/boot/grub
-/boot/initramfs*
-/boot/loader
-/boot/lost+found
-/boot/syslinux
-/boot/vmlinuz*

-/efi

-/etc/modprobe.d/blacklist.conf
-/etc/edition-tag
-/etc/adjtime
-/etc/blkid.tab
-/etc/ca-certificates
-/etc/conf.d
-/etc/credstore
-/etc/credstore.encrypted
-/etc/fancontrol
-/etc/fonts/conf.d
-/etc/group
-/etc/group-
-/etc/gshadow
-/etc/gshadow-
-/etc/hostname
-/etc/letsencrypt
-/etc/locale.conf
-/etc/localtime
-/etc/lostfiles.conf
-/etc/machine-id
-/etc/mkinitcpio.d
-/etc/network.d/ethernet-static
-/etc/NetworkManager/system-connections
-/etc/openvpn
-/etc/os-release
-/etc/pacman.d/gnupg
-/etc/passwd
-/etc/passwd-
-/etc/resolv.conf.bak
-/etc/shadow
-/etc/shadow-
-/etc/ssh/ssh_host*
-/etc/ssl
-/etc/systemd/network
-/etc/systemd/system
-/etc/systemd/user
-/etc/systemd/systemd-networkd.service

-/etc/udev/hwdb.bin
-/etc/vconsole.conf
-/etc/xml

-/etc/profile.bak
-/etc/profile.d/smallstep.bash
-/etc/profile.d/starship.bash

-/etc/pacman.d/cachyos-mirrorlist-backup
-/etc/pacman.d/cachyos-v3-mirrorlist-backup
-/etc/pacman.d/cachyos-v4-mirrorlist-backup
-/etc/modules-load.d/blacklist.conf
-/etc/modules-load.d/zfs.conf
-/etc/aclocal
-/etc/bashrc
-/etc/bashrc.bak

-/usr/bin/aconfmgr

-/usr/lib/aconfmgr
-/usr/lib/locale/locale-archive
-/usr/lib/udev/hwdb.bin


-/usr/share/mime

-/usr/var/run

-/var/db/sudo
-/var/lib
-/var/lock
-/var/log
-/var/run
# more complicated exclusion filters can be expressed by a line beginning with
# a dollar ($) sign, followed by command-line arguments to pass to find

# exclude node modules outside of the npm subfolder
$\( -not \( -path '/usr/lib/node_modules*' -and -not -path '/usr/lib/node_modules/npm/*' \) \)
# exclude dkms module folder for the kernel versions currently installed to /boot/vmlinuz-linux* in /usr/lib/modules
$\( `for kernel in /boot/vmlinuz-linux*; do version=$(file $kernel | cut -d ' ' -f 9); echo "-not ( -path /usr/lib/modules/$version -prune )";done` \)
