# Blacklist for unnecessary modules; add a module to the list to prevent autoloading as a dependency.
# Also - add another line for each with ${Modulename} install /bin/true in order to no-op direct loads of the module
#
## Run sudo depmod -ae to update module dependencies
#
#
# DEF_BAD
blacklist pkcs8_key_parser     
blacklist wmi                  
blacklist wmi_bmof             
blacklist snd_hda_intel        
blacklist kvm 
blacklist kvm_intel
blacklist i2c_dev              
blacklist i2c_piix4            
blacklist i2c_smbus            
blacklist crc32c_intel         
blacklist ghash_clmulni_intel  
blacklist intel_rapl_common    
blacklist intel_rapl_msr       
blacklist snd_intel_dspcfg     
blacklist snd_intel_sdw_acpi   
blacklist sha1_ssse3           
blacklist sha256_ssse3         
blacklist sha512_ssse3         
blacklist gigabyte_wmi         
blacklist aesni_intel          
## Not Necessarily bad, but unnecessary rn
blacklist raid6_pq             
blacklist minix                
blacklist jbd2                 
blacklist ufs                  
blacklist tun                  




install pkcs8_key_parser      /bin/true
install wmi                   /bin/true
install wmi_bmof              /bin/true
install snd_hda_intel         /bin/true
install kvm  /bin/true
install kvm_intel /bin/true
install i2c_dev               /bin/true
install i2c_piix4             /bin/true
install i2c_smbus             /bin/true
install crc32c_intel          /bin/true
install ghash_clmulni_intel   /bin/true
install intel_rapl_common     /bin/true
install intel_rapl_msr        /bin/true
install snd_intel_dspcfg      /bin/true
install snd_intel_sdw_acpi    /bin/true
install sha1_ssse3            /bin/true
install sha256_ssse3          /bin/true
install sha512_ssse3          /bin/true
install gigabyte_wmi          /bin/true
install aesni_intel           /bin/true
             ## Not Necessarily bad, but unnecessary rn /bin/true
install raid6_pq              /bin/true
install minix                 /bin/true
install jbd2                  /bin/true
install ufs                   /bin/true
install tun                   /bin/true
